package oneandone.roles

case class PermissionDetails(
  access: Option[Boolean] = None,
  accessKvmConsole: Option[Boolean] = None,
  addNode: Option[Boolean] = None,
  addSolution: Option[Boolean] = None,
  assignIp: Option[Boolean] = None,
  changeRole: Option[Boolean] = None,
//  clone: Option[Boolean] = None,
  create: Option[Boolean] = None,
  delete: Option[Boolean] = None,
  disable: Option[Boolean] = None,
  disableAutomaticCreation: Option[Boolean] = None,
  downloadFile: Option[Boolean] = None,
  enable: Option[Boolean] = None,
  manageApi: Option[Boolean] = None,
  manageAttachedServerIps: Option[Boolean] = None,
  manageAttachedServers: Option[Boolean] = None,
  manageDvd: Option[Boolean] = None,
  managePorts: Option[Boolean] = None,
  manageProcesses: Option[Boolean] = None,
  manageRules: Option[Boolean] = None,
  manageSnapshot: Option[Boolean] = None,
  manageUsers: Option[Boolean] = None,
  modify: Option[Boolean] = None,
  modifyResources: Option[Boolean] = None,
  reinstall: Option[Boolean] = None,
  release: Option[Boolean] = None,
  removeNode: Option[Boolean] = None,
  resize: Option[Boolean] = None,
  restart: Option[Boolean] = None,
  setDescription: Option[Boolean] = None,
  setEmail: Option[Boolean] = None,
  setName: Option[Boolean] = None,
  setNetworkInfo: Option[Boolean] = None,
  setReverseDns: Option[Boolean] = None,
  show: Option[Boolean] = None,
  shutdown: Option[Boolean] = None,
  start: Option[Boolean] = None,
) {}
